[package]
name = "yeokcham-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "yeokcham"
path = "src/main.rs"

[[bin]]
name = "git-remote-yeokcham"
path = "src/remote_helper.rs"

[dependencies]
hex.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
yeokcham-core = { path = "../yeokcham-core" }
zeroize.workspace = true
