(lang dune 3.23)
(name yeokcham)
(generate_opam_files true)
(source (github gongahkia/yeokcham))
(authors "Gabriel Ong Zhe Mian")
(maintainers "Gabriel Ong Zhe Mian <angryapplegravy@gmail.com>")
(license MIT)

(package
 (name yeokcham)
 (synopsis "Experimental model-first local-first version control")
 (description "A local-first VCS separating scratch, intent, and release history.")
 (allow_empty))
