(library
 (name yeokcham_v4_local_service)
 (libraries
  unix
  yeokcham_hash
  yeokcham_snapshot
  yeokcham_v4_model
  yeokcham_v4_bootstrap
  yeokcham_v4_package
  yeokcham_v4_lsp_sidecar
  yeokcham_v4_proposal
  yeokcham_v4_recovery
  yeokcham_v4_receipt
  yeokcham_v4_restore_journal
  yeokcham_v4_restore_proof
  yeokcham_v4_store
  yeokcham_v4_semantic_config
  yeokcham_v4_transport
  yeokcham_v4_trust))
