[package]
name = "yeokcham-server"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "yeokcham-server"
path = "src/main.rs"

[dependencies]
base64.workspace = true
getrandom.workspace = true
hex.workspace = true
libc.workspace = true
subtle.workspace = true
yeokcham-core = { path = "../yeokcham-core" }
zeroize.workspace = true

[dev-dependencies]
uuid.workspace = true
